### ISSUE TITLE
Reduce the compiler cache footprint

### ISSUE THREAD

**Issue by thetheodor** [DeadCodeProductions/dead#10]
- [ ] Don't store unnecessary files, we only need the compiler itself and its strict dependencies
- [ ] Integrate [elfshaker](https://github.com/elfshaker/elfshaker), this could potentially make the cache redistributable

**Comment by Quarub** [comment]
@thetheodor I think is partially addressed in `ccbuilder` (smaller builds) and the cache distribution seems to be a nice to have requiring a bit too much effort for now.

Feel free to reopen it.
