### ISSUE TITLE
some doubts

### ISSUE THREAD

**Issue by codyhu** [DeadCodeProductions/dead#47]
Hello, after reading the paper, I think it is a very interesting and meaningful work.

In the meantime, I have some specific questions and would like your answers.

1.  I have no doubts about the current way of inserting the DCEMarker and think it is a very effective. The question is, how exactly do I construct my own test set? Or, how do I add the corresponding DCEMarker to my local test case？
2. 
On the basis of the first question, if I can insert the corresponding DCEMarker into some benchmarks, such as spec, can it also help the compiler to optimize its performance?

Hope to get your reply ASAP.

Thx again.

**Comment by Quarub** [comment]
Hi @codyhu 

you can add markers to your programs by invoking `instrument_program` from the [dead_instrumenter](https://github.com/DeadCodeProductions/dead_instrumenter) package on your code. An example use can be found [here](https://github.com/DeadCodeProductions/dead/blob/06c72dc286ea1a7a83d22d545dfed7675e348d96/generator.py#L124).

The markers hinder optimizations. This, for example, has been pointed out in issue #30 . 
If you want to reuse the information gained from the markers on the benchmark, you'll mostly be out of luck as there's not much dead code in more realistic code (compared to csmith code). Thus, you have few opportunities to optimize in the first place.

**Comment by codyhu** [comment]
Got it, Thx.

**Comment by Quarub** [comment]
Closing because it seems to be resolved
